name: 'Build'

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          TOOLCHAIN_VERSION: 1.77
          UPLOAD_MODE: none
          ARCHIVE_NAME: custome-binary.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
